In [13]:
import pandas as pd
import numpy as np
# import seaborn as sns

pd.set_option('display.float_format', '{:,.2f}'.format)

In [5]:
df = pd.read_excel('20-25 Payments.xlsx')
org = pd.read_excel('Organizations.xlsx')
contr = pd.read_excel("Final.xlsx")

In [7]:
df.groupby([ 'Payer Code', 'Organization Name',])['Amount'].sum().reset_index()

,Payer Code,Organization Name,Amount
0,111001001,STATE HOUSE - HQTRS,"119,241,827,626.66"
1,111001002,STATE HOUSE OPERATIONS - PRESIDENT,"27,334,353,484.81"
2,111001003,STATE HOUSE OPERATIONS - VICE PRESIDENT,"5,441,820,530.78"
3,111001004,OFFICE OF THE CHIEF OF STAFF TO THE PRESIDENT,"10,911,521,010.84"
4,111001005,OFFICE OF THE CHIEF SECURITY OFFICER TO THE PR...,"1,022,730,234.37"
...,...,...,...
886,554008001,OFFICE OF THE SENIOR SPECIAL ASSISTANT TO THE ...,"115,152,415,649.90"
887,554009001,NATIONAL SENIOR CITIZEN CENTRE,"227,782,674.15"
888,555001001,FEDERAL MINISTRY OF YOUTH DEVELOPMENT - HQTRS,"1,345,896,113.77"
889,555002001,NATIONAL YOUTH SERVICE CORPS (NYSC),"48,863,409,240.84"
890,555003001,CITIZENSHIP & LEADERSHIP TRAINING CENTRE,"368,999,274.27"

In [10]:
cont = pd.read_excel("Final.xlsx")
cont[['Beneficiary Name', 'RC']]

                                        Beneficiary Name       RC
0      A. A. MACHIKA & COMPANY ATTORNEYS AND LEGAL CO...  7202811
1                 AL-DAHA INTERNATIONAL VENTURES LIMITED  1817669
2                         DALOB EXCEL GLOBAL ENTERPRISES  3532012
3                            FRANK MALUZE AND ASSOCIATES   804829
4                             KHAIRAT TRAVEL & TOURS LTD  1975001
...                                                  ...      ...
21227                HAYES MULTI SYSTEMES INVESTMENT LTD  1243601
21228                                     KAGO NIG. LTD.    96977
21229                                 OLODO NIG. LIMITED   257935
21230                          AMAZEMENT NIGERIA LIMITED   701195
21231                        CONCEPT CONNECTION SERV LTD   867701

[21232 rows x 2 columns]

In [11]:
merged = df.merge(cont[['Beneficiary Name', 'RC']], how='left', on='Beneficiary Name')

In [13]:
merged.to_excel('A.xlsx', index=False)
merged.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Organization,RC
0,1000659435-65,232002001,DEPARTMENT OF PETROLEUM RESOURCES,SULEIMAN ILIYASU LAWAL TANIMU,"5,282,111.00",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,NaN
1,1000659420-23,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKEKHIDE JENNIFER OSHIONE,"8,750,704.78",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,NaN
2,1000659435-69,232002001,DEPARTMENT OF PETROLEUM RESOURCES,NJOKU KELECHI CHIAKA,"5,282,929.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,NaN
3,1000659420-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,BIGHORO SYLVESTER EDIRIN,"7,569,966.14",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,NaN
4,1000659435-1,232002001,DEPARTMENT OF PETROLEUM RESOURCES,UMARU AHMADU,"5,841,144.67",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES,NaN

In [3]:
merged = df.merge(org, how='left', on='Organization Name')
merged.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,...,Location,Organization,Acronym,Website,2020,2021,2022,2023,2024,Total
0,1000659435-65,232002001,DEPARTMENT OF PETROLEUM RESOURCES,SULEIMAN ILIYASU LAWAL TANIMU,"5,282,111.00",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,DEPARTMENT OF PETROLEUM RESOURCES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000659420-23,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Ekekhide Jennifer Oshione,"8,750,704.78",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,DEPARTMENT OF PETROLEUM RESOURCES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000659435-69,232002001,DEPARTMENT OF PETROLEUM RESOURCES,NJOKU KELECHI CHIAKA,"5,282,929.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,DEPARTMENT OF PETROLEUM RESOURCES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000659420-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Bighoro Sylvester Edirin,"7,569,966.14",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,DEPARTMENT OF PETROLEUM RESOURCES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000659435-1,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Umaru Ahmadu,"5,841,144.67",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,DEPARTMENT OF PETROLEUM RESOURCES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
merged.to_excel('2020 to 2025 Gov Expenditure Dataset.xlsx', index=False)

In [6]:
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA
0,1000659435-65,232002001,DEPARTMENT OF PETROLEUM RESOURCES,SULEIMAN ILIYASU LAWAL TANIMU,"5,282,111.00",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources
1,1000659420-23,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Ekekhide Jennifer Oshione,"8,750,704.78",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources
2,1000659435-69,232002001,DEPARTMENT OF PETROLEUM RESOURCES,NJOKU KELECHI CHIAKA,"5,282,929.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources
3,1000659420-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Bighoro Sylvester Edirin,"7,569,966.14",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources
4,1000659435-1,232002001,DEPARTMENT OF PETROLEUM RESOURCES,Umaru Ahmadu,"5,841,144.67",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources

In [5]:
df['Organization Name'] = df['Organization Name'].str.upper()

In [30]:
df[df['Year'] == 2024].groupby(['Organization Name'])['Amount'].sum().reset_index().to_excel('bob.xlsx', index=False)

In [47]:
org = pd.read_excel('Organizations.xlsx')

In [39]:
group = pd.read_excel('group.xlsx', sheet_name='2024')
org = org.drop(2024, axis=1)
org = org.merge(group, how='left', on='Organization Name')

In [40]:
org.head()

,Organization Name,COFOG Code,MDA,Location,Region,Organization,Acronym,Website,Total,2020,2021,2022,2023,Amount
0,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,7,Federal Ministry of Health & Social Welfare,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,NaN,NaN,"9,043,227,749.81","931,391,933.56","1,402,157,135.00","1,163,200,761.47","1,941,935,094.34","3,604,542,825.43"
1,"ABUBAKAR TAFAWA BALEWA UNIVERSITY, BAUCHI",9,Federal Ministry of Education,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY,NaN,NaN,"18,373,149,899.68","631,524,012.12","4,422,086,499.00","4,831,735,707.41","3,285,811,462.68","5,201,992,218.48"
2,ACCIDENT AND INVESTIGATION BUREAU,3,Federal Ministry of Aviation & Aerospace Devel...,Lagos,South West,ACCIDENT AND INVESTIGATION BUREAU,NaN,NaN,"1,091,338,215.98",NaN,"203,886,874.80","887,451,341.16",NaN,NaN
3,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,9,Office of the Head of the Civil Service of the...,Lagos,South West,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,NaN,NaN,"1,401,100,610.61","125,594,327.33","184,115,212.60","235,564,776.94","461,283,993.43","394,542,300.33"
4,"ADMIRALTY UNIVERSITY OF NIGERIA, IBUSA, DELTA ...",9,Federal Ministry of Defence,Delta,South South,ADMIRALTY UNIVERSITY OF NIGERIA,NaN,NaN,"1,807,294,753.10",NaN,NaN,NaN,NaN,"1,807,294,753.10"

In [41]:
org['Total'] = sum([org[2020], org[2021], org[2022], org[2023], org['Amount']])

In [51]:
org.groupby('Organization')[[2020, 2021, 2022, 2023, 2024, 'Total']].sum().reset_index().to_excel('bob.xlsx', index=False)

In [42]:
org.to_excel('Organizations_Final.xlsx', index=False)

In [2]:
locations = org.groupby("Location")['Total'].sum().reset_index()

In [15]:
tw20 = org.groupby("Location")[2024].sum().reset_index()

In [16]:
locations = locations.merge(tw20, how='left', on='Location')

In [17]:
locations

,Location,Total,2020,2021,2022,2023,2024
0,Aba,"21,869,762,285.84","1,092,690,588.72","2,994,424,700.53","2,997,874,974.32","7,282,018,932.58","7,502,753,089.69"
1,Abia,"1,076,765,275,436.67","67,451,544,295.85","221,755,805,354.38","182,231,641,162.03","287,086,932,837.74","318,239,351,786.67"
2,Adamawa,"1,796,683,431,038.39","122,416,493,030.93","353,704,845,118.54","302,901,499,866.45","483,727,422,088.27","533,933,170,934.20"
3,Akwa Ibom,"885,164,688,129.34","46,342,838,415.20","191,092,511,340.73","155,373,535,472.70","229,862,140,451.42","262,493,662,449.29"
4,Anambra,"1,168,327,099,707.25","69,271,334,522.51","236,026,194,515.59","196,708,344,326.74","314,223,215,516.50","352,098,010,825.91"
5,Bauchi,"1,096,725,803,367.48","67,560,748,702.15","223,631,991,415.66","184,399,489,460.26","293,421,267,316.05","327,712,306,473.36"
6,Bayelsa,"1,039,176,338,991.73","59,597,511,588.86","207,447,607,392.25","180,093,860,080.25","275,899,821,090.30","316,137,538,840.07"
7,Benue,"1,187,105,024,555.57","70,617,984,849.74","242,035,803,167.83","202,563,915,492.04","317,728,343,746.50","354,158,977,299.46"
8,Borno,"1,173,952,322,019.69","70,260,328,014.28","224,735,688,273.49","191,394,548,064.02","293,162,629,308.31","394,399,128,359.59"
9,"Borno, Yobe","259,089,423.33","33,789,524.35","26,330,995.85","34,094,459.17","74,834,138.93","90,040,305.03"
10,Cross River,"944,592,890,291.01","55,592,779,153.31","198,104,359,732.14","161,142,023,965.26","247,065,895,406.22","282,687,832,034.08"
11,Delta,"1,730,204,932,842.14","113,052,688,806.12","311,193,056,634.65","264,088,510,088.09","398,508,085,960.58","643,362,591,352.70"
12,Ebonyi,"559,507,644,165.97","31,327,992,162.64","106,207,705,380.38","85,121,825,965.43","153,534,454,952.55","183,315,665,704.97"
13,Edo,"996,892,445,961.26","55,771,058,174.11","203,924,457,817.22","171,559,888,241.39","272,419,031,066.69","293,218,010,661.85"
14,Ekiti,"1,049,441,776,448.27","54,749,433,606.61","213,474,501,058.67","177,843,622,483.97","277,662,188,154.50","325,712,031,144.52"
15,Enugu,"1,189,691,721,955.67","57,603,520,121.91","231,480,520,576.24","196,078,174,030.75","331,729,401,217.32","372,800,106,009.45"
16,FCT,"31,186,176,254,938.47","2,458,192,758,979.97","5,565,794,207,719.51","5,945,946,807,032.52","7,973,774,134,967.49","9,242,468,346,238.98"
17,Foreign,"14,666,760,053.64","2,212,608,216.79","2,794,762,983.62","1,257,250,625.19","4,885,898,671.30","3,516,239,556.74"
18,Gombe,"1,115,979,603,567.34","54,292,696,286.24","218,869,885,030.75","189,595,023,428.40","298,453,763,806.84","354,768,235,015.11"
19,Imo,"576,181,623,751.51","40,875,615,473.43","103,498,340,381.28","90,136,570,879.77","161,658,600,484.67","180,012,496,532.36"
20,Jigawa,"1,077,085,100,372.43","61,792,183,016.45","214,471,542,112.39","185,323,661,147.25","287,358,346,873.71","328,139,367,222.63"
21,Kaduna,"1,434,313,574,745.36","80,720,017,439.06","280,114,749,517.48","235,056,738,012.93","393,442,703,136.68","444,979,366,639.21"
22,Kano,"1,287,467,706,144.00","72,517,776,015.96","273,003,219,303.58","233,414,494,952.86","344,943,182,652.82","363,589,033,218.78"
23,Katsina,"2,026,519,706,599.94","124,619,463,643.60","406,370,148,042.29","341,058,695,784.70","538,429,198,032.82","616,042,201,096.53"
24,Kebbi,"1,037,630,886,223.34","59,307,143,769.73","206,257,451,790.30","179,952,326,083.58","275,899,821,090.30","316,214,143,489.43"
25,Kogi,"1,284,302,432,636.68","79,322,217,447.85","263,740,446,133.63","223,459,443,559.71","339,757,349,988.70","378,022,975,506.79"
26,Kwara,"687,719,373,916.29","35,764,205,801.31","144,512,847,036.22","124,476,172,889.06","169,018,262,567.04","213,947,885,622.66"
27,Lagos,"1,753,523,559,328.53","106,948,992,982.24","321,044,283,041.51","319,682,909,707.23","488,901,336,044.07","516,946,037,553.48"
28,Nasarawa,"1,250,314,385,633.77","73,466,891,570.67","253,112,913,433.27","215,329,449,941.24","334,009,881,528.24","374,395,249,160.35"
29,Niger,"1,623,016,706,307.11","91,960,626,428.24","319,967,007,301.16","282,927,491,540.32","442,851,646,818.26","485,309,934,219.13"
30,Ogun,"905,427,154,605.98","56,511,678,166.76","182,149,249,575.48","151,096,365,207.53","243,351,351,241.01","272,318,510,415.20"
31,Ondo,"1,153,602,290,419.56","69,739,434,093.06","236,435,511,912.73","195,992,950,203.78","306,700,838,652.07","344,733,555,557.92"
32,Osun,"838,902,017,558.86","44,595,367,635.72","174,903,132,267.88","144,687,366,047.83","221,772,835,362.83","252,943,316,244.60"
33,Owerri,"378,312,267,447.93","18,442,040,391.73","83,193,616,274.35","67,650,077,719.85","95,523,903,550.19","113,502,629,511.81"
34,Oyo,"1,153,515,923,422.34","54,110,283,037.14","214,697,495,999.31","190,873,799,751.71","325,625,657,871.13","368,208,686,763.05"
35,Plateau,"1,201,673,093,078.40","76,385,879,532.81","241,501,701,968.39","203,389,848,640.72","321,343,438,436.52","359,052,224,499.96"
36,Rivers,"852,537,029,795.97","48,348,039,336.73","177,291,770,126.57","146,844,060,575.98","225,410,689,262.08","254,642,470,494.61"
37,Sokoto,"530,923,084,474.14","33,522,266,890.45","112,706,930,004.09","91,267,940,601.26","139,116,329,770.32","154,309,617,208.02"
38,Taraba,"994,831,267,189.16","59,163,571,049.35","197,256,519,142.38","170,711,877,388.73","265,035,908,853.75","302,663,390,754.95"
39,Yobe,"1,254,446,518,095.29","73,780,055,293.63","254,045,480,578.62","215,244,568,594.01","335,142,716,964.15","376,233,696,664.88"
40,Zamfara,"1,225,530,500,448.34","72,278,835,854.08","250,155,755,187.58","212,446,833,680.80","325,595,027,159.75","365,054,048,566.13"

In [18]:
locations.to_excel("States.xlsx", index=False)

In [20]:
zones = {
    "South West": ["Lagos","Ogun","Oyo","Osun","Ondo","Ekiti"],
    "South East": ["Abia","Anambra","Ebonyi","Enugu","Imo"],
    "South South": ["Akwa Ibom","Bayelsa","Cross River","Delta","Edo","Rivers"],
    "North Central": ["Benue","Kogi","Kwara","Nasarawa","Niger","Plateau","FCT"],
    "North East": ["Adamawa","Bauchi","Borno","Gombe","Taraba","Yobe"],
    "North West": ["Jigawa","Kaduna","Kano","Katsina","Kebbi","Sokoto","Zamfara"]
}

def get_region(state):
    for region, states in zones.items():
        if state in states:
            return region
    return 'Foreign'

In [23]:
org.head()

,Organization Name,COFOG Code,MDA,Location,Region,Organization,Acronym,Website,2020,2021,2022,2023,2024,Total
0,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,7,Federal Ministry of Health & Social Welfare,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,NaN,NaN,"931,391,933.56","1,402,157,135.01","1,163,200,761.47","1,941,935,094.34","3,604,542,825.43","9,043,227,749.81"
1,"ABUBAKAR TAFAWA BALEWA UNIVERSITY, BAUCHI",9,Federal Ministry of Education,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY,NaN,NaN,"631,524,012.12","4,422,086,498.99","4,831,735,707.41","3,285,811,462.68","5,201,992,218.48","18,373,149,899.68"
2,ACCIDENT AND INVESTIGATION BUREAU,3,Federal Ministry of Aviation & Aerospace Devel...,Lagos,South West,ACCIDENT AND INVESTIGATION BUREAU,NaN,NaN,NaN,"203,886,874.82","887,451,341.16",NaN,NaN,"1,091,338,215.98"
3,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,9,Office of the Head of the Civil Service of the...,Lagos,South West,ADMINISTRATIVE STAFF COLLEGE OF NIGERIA,NaN,NaN,"125,594,327.33","184,115,212.58","235,564,776.94","461,283,993.43","394,542,300.33","1,401,100,610.61"
4,"ADMIRALTY UNIVERSITY OF NIGERIA, IBUSA, DELTA ...",9,Federal Ministry of Defence,Delta,South South,ADMIRALTY UNIVERSITY OF NIGERIA,NaN,NaN,NaN,NaN,NaN,NaN,"1,807,294,753.10","1,807,294,753.10"

In [22]:
org['Region'] = org['Location'].apply(get_region)

In [24]:
org.to_excel("Organizations_Final.xlsx", index=False)

In [52]:
df['Beneficiary Name'] = df['Beneficiary Name'].str.upper()

In [53]:
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Organization
0,1000659435-65,232002001,DEPARTMENT OF PETROLEUM RESOURCES,SULEIMAN ILIYASU LAWAL TANIMU,"5,282,111.00",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
1,1000659420-23,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKEKHIDE JENNIFER OSHIONE,"8,750,704.78",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
2,1000659435-69,232002001,DEPARTMENT OF PETROLEUM RESOURCES,NJOKU KELECHI CHIAKA,"5,282,929.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
3,1000659420-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,BIGHORO SYLVESTER EDIRIN,"7,569,966.14",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES
4,1000659435-1,232002001,DEPARTMENT OF PETROLEUM RESOURCES,UMARU AHMADU,"5,841,144.67",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4,Federal Ministry of Petroleum Resources,DEPARTMENT OF PETROLEUM RESOURCES

In [54]:
df.to_excel('2020 to 2025 Gov Expenditure Dataset.xlsx', index=False)

In [9]:
df[df['Type']=="Contractor"].groupby('Beneficiary Name')['Amount'].sum().reset_index().to_excel("Contractors.xlsx", index=False)

In [10]:
df = pd.read_excel('Contractors.xlsx')
df["Contractors_Cleaned"] = df["Beneficiary Name"].str.replace(r"\bLIMITED\b|\bLTD\b", "", case=False, regex=True)
df.head()

,Beneficiary Name,Amount,RC,Registered Name,Date of Registration,Status,Nature of Business,Type of Registration,Contractors_Cleaned
0,A. A. MACHIKA & COMPANY ATTORNEYS AND LEGAL CO...,"5,000,000.00",7202811,A. A. MACHIKA & COMPANY ATTORNEYS AND LEGAL CO...,2023-10-31,Active,NaN,Business Name,A. A. MACHIKA & COMPANY ATTORNEYS AND LEGAL CO...
1,AL-DAHA INTERNATIONAL VENTURES LIMITED,"5,000,000.00",1817669,AL-DAHA INTERNATIONAL VENTURES LIMITED,2021-07-14,Active,Construction of Buildings,Company,AL-DAHA INTERNATIONAL VENTURES
2,DALOB EXCEL GLOBAL ENTERPRISES,"5,000,000.00",3532012,DALOB EXCEL GLOBAL ENTERPRISES,2021-12-13,Inactive,NaN,Business Name,DALOB EXCEL GLOBAL ENTERPRISES
3,FRANK MALUZE AND ASSOCIATES,"5,000,000.00",804829,FRANK MALUZE & ASSOCIATES,1991-09-18,Active,NaN,Business Name,FRANK MALUZE AND ASSOCIATES
4,KHAIRAT TRAVEL & TOURS LTD,"5,000,000.00",1139533,KHAIRAT TRAVEL & TOURS LTD,2013-09-03,Active,Travel Agents & Tour Operators,Company,KHAIRAT TRAVEL & TOURS

In [14]:
merged.groupby('RC')['Amount'].sum()

RC
92151         6,668,338.13
305062        6,660,640.68
660539        6,641,395.94
695519       20,007,000.00
784291        6,636,017.52
                  ...
UY/00833     22,740,571.86
UY/008725    43,651,720.00
UY006757      5,161,541.75
YLZ0002484    6,216,279.07
YLZ0002700    8,088,770.25
Name: Amount, Length: 20254, dtype: float64

In [15]:
final = merged.groupby('RC')['Amount'].sum().reset_index().merge(cont, how='left', on='RC')
final.head()

,RC,Amount_x,Beneficiary Name,Amount_y,Registered Name,Date of Registration,Status,Nature of Business,Type of Registration,Contractors_Cleaned,Unnamed: 9
0,92151,"6,668,338.13",HASSAN PETROLEUM NIG. LTD,"6,668,338.13",HASSAN PETROLEUM (NIG) LTD,1987-02-19 00:00:00,STRUCK-OFF (Visit CAC and update your status),Unspecified,COMPANY,HASSAN PETROLEUM NIG,NaN
1,305062,"6,660,640.68",SOLIA INTER LTD,"6,660,640.68",SOLIA INTERNATIONAL LIMITED,1996-12-11 00:00:00,ACTIVE,General Merchandise,COMPANY,SOLIA INTER,NaN
2,660539,"6,641,395.94",EFLAYE INTÃ¢Â€Â™L LTD,"6,641,395.94",EFLAYE INTL LIMITED,2006-07-17 00:00:00,ACTIVE,Construction of Buildings,COMPANY,EFLAYE INT'L,NaN
3,695519,"20,007,000.00",INEXHAUSTIBLE RICHES & GLORY,"20,007,000.00",INEXHAUSTIBLE RICHES AND GLORY LIMITED,2007-06-15 00:00:00,INACTIVE (Visit CAC and update your status),Unspecified,COMPANY,INEXHAUSTIBLE RICHES & GLORY,NaN
4,784291,"6,636,017.52",TAYLO NIGIRIA LTD,"6,636,017.52",TAYLO NIGERIA LIMITED,2008-11-06 00:00:00,INACTIVE (Visit CAC and update your status),Unspecified,COMPANY,TAYLO NIGIRIA,NaN

In [16]:
final.to_excel("B.xlsx", index=False)

In [3]:
df = pd.read_excel('20-25 Payments.xlsx')

In [5]:
df[df['Type'] == 'Contractor']["Beneficiary Name"].unique()

array(['DASH BUILDING SERVICES', 'IBTC PENSION MANAGERS',
       'SIGMA VAUGN STERLING PENSIONS LIMITED', ...,
       'DRIS LUJI GLOBAL NIGERIA LIMITED',
       'ATOLINKS ENERGY SOLUTIONS LIMITED', 'BOLNIFTOP NIGERIA LTD'],
      dtype=object)

In [6]:
bob = pd.DataFrame()
bob['Contractors'] = df[df['Type'] == 'Contractor']["Beneficiary Name"].unique()

In [7]:
bob.to_excel("Contractors_FINAL.xlsx", index=False)

In [53]:
df = pd.read_excel('20-25 Payments.xlsx')
org = pd.read_excel('Organizations.xlsx')
contr = pd.read_excel("Final.xlsx")

In [76]:
contr = pd.read_excel("Final.xlsx")
contr = contr[["Beneficiary Name", "Date of Registration"]]

In [74]:
contr = contr[["Beneficiary Name", "RC", "Registered Name"]]

In [77]:
df = df.merge(contr, how="left", on="Beneficiary Name")
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,...,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description,is_duplicate_payment,risk_score,risk_band,Registered Name,Date of Registration
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,NaN,1,0,0.00,0,0,1,LOW,NaN,NaN
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,NaN,1,0,0.00,0,0,1,LOW,NaN,NaN
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,NaN,1,0,0.00,0,0,1,LOW,NaN,NaN
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,NaN,1,0,0.00,0,0,1,LOW,NaN,NaN
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,NaN,1,0,0.00,0,0,1,LOW,NaN,NaN

In [56]:
df["is_beneficiary_individual"] = (df["Type"] == "Individual").astype(int)
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization,RC,is_beneficiary_individual
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1

In [57]:
df["is_beneficiary_unknown"] = (df["Type"] == "Unknown").astype(int)
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0

In [58]:
df["contractor_not_registered"] = np.where(
    df["Type"] == "Contractor", 
    df["RC"].notna().astype(int), 
    np.nan
)
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN

In [59]:
df["contractor_not_registered"] = df["contractor_not_registered"].map({0: 1, 1: 0})

In [60]:
df["has_description"] = (df["Description"].astype(str).str.strip().replace("nan", "").ne("")).astype(int)
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,1
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,1
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,1
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,1
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,4.00,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,1

In [61]:
df["has_description"] = 1 - df["has_description"]

In [62]:
df[df["Type"]=="Contractor"]

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,COFOG Code,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description
91,1000659314-2,521026016,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,DASH BUILDING SERVICES,"6,559,867.62",PAYMENT FOR THE CONSTRUCTION OF TRAUMA CENTER ...,2020-01-29,1,Contractor,2020,7.00,Federal Ministry of Health & Social Welfare,Bauchi,North East,ABUBAKAR TAFAWA BALEWA UNIVERSITY TEACHING HOS...,NaN,0,0,1.00,0
689,1000660383-37,517005001,JOINT ADMISSIONS MATRICULATION BOARD,IBTC PENSION MANAGERS,"11,458,243.68",JAN 2020 JOINT ADMISSIONS AND -IBTC Pension M...,2020-01-31,1,Contractor,2020,9.00,Federal Ministry of Education,FCT,North Central,JOINT ADMISSIONS MATRICULATION BOARD,510990,0,0,0.00,0
690,1000660333-68,517017001,NATIONAL TEACHERS INSTITUTE,SIGMA VAUGN STERLING PENSIONS LIMITED,"5,881,972.08",JAN 2020 NATIONAL TEACHERS IN -Sigma Vaugn St...,2020-01-31,1,Contractor,2020,9.00,Federal Ministry of Education,Kaduna,North West,NATIONAL TEACHERS INSTITUTE,NaN,0,0,1.00,0
691,1000660549-87,521027021,"FEDERAL MEDICAL CENTRE, MAKURDI",PREMIUM PENSION LIMITED,"13,860,517.62",JAN 2020 MEDICAL CENTRE MAKUR -Premium Pensio...,2020-01-31,1,Contractor,2020,7.00,Federal Ministry of Health & Social Welfare,Benue,North Central,FEDERAL MEDICAL CENTRE,619488,0,0,0.00,0
692,1000660311-23,233008001,NATIONAL IRON ORE MINING PROJECT - ITAKPE,PREMIUM PENSION LIMITED,"7,358,787.94",JAN 2020 NATIONAL IRON ORE MI -Premium Pensio...,2020-01-31,1,Contractor,2020,4.00,Federal Ministry of Steel Development,Kogi,North Central,NATIONAL IRON ORE MINING PROJECT,619488,0,0,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398936,1001314029-1,234001001,FEDERAL MINISTRY OF WORKS,VOLATIX PRODUCTS LIMITED,"540,035,111.11",BEING FINAL PAYMENT FOR SLUMP UPGRADE: CONSTRU...,2025-12-31,12,Contractor,2025,4.00,Federal Ministry of Works,FCT,North Central,FEDERAL MINISTRY OF WORKS,1639221,0,0,0.00,0
398940,1001315133-4,234001001,FEDERAL MINISTRY OF WORKS,FIRST BROAD INTERNATIONAL LIMITED,"23,494,538.35",BEING PAYMENT FOR THE LIMITED REHABILITATION O...,2025-12-31,12,Contractor,2025,4.00,Federal Ministry of Works,FCT,North Central,FEDERAL MINISTRY OF WORKS,398117,0,0,0.00,0
398941,1001351528-4,234001001,FEDERAL MINISTRY OF WORKS,VISIBLE CONSTRUCTION LIMITED,"814,252,471.52",BEING PAYMENT FOR THE CONSTRUCTION OF IKORODU ...,2025-12-31,12,Contractor,2025,4.00,Federal Ministry of Works,FCT,North Central,FEDERAL MINISTRY OF WORKS,714362,0,0,0.00,0
398946,1001376571-28,555001001,FEDERAL MINISTRY OF YOUTH DEVELOPMENT - HQTRS,ND GENERAL COMPUTERS NIG LTD,"25,217,380.00",BEING PAYMENT TO M/S ND GENERAL COMPUTERS NIG ...,2025-12-31,12,Contractor,2025,10.00,Federal Ministry of Youth Development,FCT,North Central,FEDERAL MINISTRY OF YOUTH DEVELOPMENT,775487,0,0,0.00,0
398947,1001374872-8,517018019,YABA COLLEGE OF TECHNOLOGY,JAFFA TECHNOLOGIES LIMITED,"16,893,421.97",PAYMENT FOR THE PURCHASE OF REAGENTS,2025-12-31,12,Contractor,2025,9.00,Federal Ministry of Education,Lagos,South West,YABA COLLEGE OF TECHNOLOGY,739788,0,0,0.00,0

In [63]:
dup_key_cols = ["Payer Code", "Organization Name", "Beneficiary Name", "Amount", "Date", "Description"]
df["is_duplicate_payment"] = (df[dup_key_cols].duplicated(keep=False)).astype(int)
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,...,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description,is_duplicate_payment
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,0,0
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,0,0
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,0,0
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,0,0
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,Federal Ministry of Petroleum Resources,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,NaN,0,0

In [64]:
df[df[dup_key_cols].duplicated()]

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,...,MDA,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description,is_duplicate_payment
2317,1000661028-1,116007001,NIGERIAN DEFENCE COLLEGE,NATIONAL DEFENCE COLLEGE CAPITAL A/C,"200,000,000.00",BEING PAYMENT FOR REGIONAL TOUR,2020-02-04,2,MDA,2020,...,Federal Ministry of Defence,FCT,North Central,NIGERIAN DEFENCE COLLEGE,NaN,0,0,NaN,0,1
2322,1000661133-2,116003001,NIGERIAN ARMY,IPPIS TRANSACTION ACCOUNT,"222,916,256.90",NOV 2019 Salary NIGERIAN ARMY,2020-02-05,2,MDA,2020,...,Federal Ministry of Defence,FCT,North Central,NIGERIAN ARMY,NaN,0,0,NaN,0,1
2331,1000661134-1,116003001,NIGERIAN ARMY,IPPIS TRANSACTION ACCOUNT,"4,750,302,154.00",NOV 2019 Salary NIGERIAN ARMY,2020-02-05,2,MDA,2020,...,Federal Ministry of Defence,FCT,North Central,NIGERIAN ARMY,NaN,0,0,NaN,0,1
2333,1000661156-1,116003001,NIGERIAN ARMY,HQ NIGERIAN ARMY FINANCE CORPS,"8,000,000,000.00",NaN,2020-02-05,2,MDA,2020,...,Federal Ministry of Defence,FCT,North Central,NIGERIAN ARMY,NaN,0,0,NaN,1,1
2456,1000661302-25,232003001,PETROLEUM TRAINING INSTITUTE,PENCOM IFOPETROLEUM TRAINING INSTITUTE,"31,404,531.48","January, 2020 Social Contribution from Salary ...",2020-02-07,2,MDA,2020,...,Federal Ministry of Petroleum Resources,Delta,South South,PETROLEUM TRAINING INSTITUTE,NaN,0,0,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394952,1001371716-3,116018001,DEFENCE SPACE ADMINISTRATION,DEFENCE SPACE ADMINISTRATION,"10,000,000.00",PAYMENT OF OVERHEAD FOR THE MONTH OF OCTOBER 2025,2025-12-30,12,MDA,2025,...,Federal Ministry of Defence,FCT,North Central,DEFENCE SPACE ADMINISTRATION,NaN,0,0,NaN,0,1
395143,1001371686-12,116018002,"DEFENCE SPACE SCHOOL, OROGUN, DELTA STATE",DEFENCE SPACE ADMINISTRATION,"10,000,000.00",PAYMENT OF OVERHEAD FOR THE MONTH OF OCTOBER 2025,2025-12-30,12,MDA,2025,...,Federal Ministry of Defence,Delta,South South,DEFENCE SPACE SCHOOL,NaN,0,0,NaN,0,1
395470,1001370272-5,517026033,FGC RUBBOCHI,GOBIR SNACKS EMPIRE AND EVENT CATERING SERVICES,"5,643,000.00",BEING PAYMENT FOR THE SUPPLY OF FOOD ITEMS TO ...,2025-12-30,12,Contractor,2025,...,Federal Ministry of Education,FCT,North Central,FEDERAL GOVERNMENT COLLEGE,GOBIR SNACKS EMPIRE AND EVENT CATERING SERVICES,0,0,0.00,0,1
396836,1001374982-4,521027002,UNIVERSITY OF UYO TEACHING HOSPITAL,UKOMA VENTURES LIMITED,"6,110,000.00",Being Payment for Supply of 5000L of Diesel to...,2025-12-31,12,Contractor,2025,...,Federal Ministry of Health & Social Welfare,Akwa Ibom,South South,UNIVERSITY OF UYO TEACHING HOSPITAL,422571,0,0,0.00,0,1
398231,1001374602-4,521026024,FEDERAL UNIVERSITY OF HEALTH SCIENCES TEACHING...,TRENDS VENERATE NIGERIA LIMITED,"11,591,699.84",BEING PAYMENT FOR THE RENOVATION OF DOCTORS QU...,2025-12-31,12,Contractor,2025,...,Federal Ministry of Health & Social Welfare,Benue,North Central,FEDERAL UNIVERSITY OF HEALTH SCIENCES TEACHING...,119697,0,0,0.00,0,1

In [65]:
df["contractor_not_registered"] = df["contractor_not_registered"].fillna(0)

In [66]:
# Weights
UNKNOWN_BENEFICIARY = 4
DUPLICATE_PAYMENT = 3
UNREGISTERED_CONTRACTOR = 2
NO_DESCRIPTION = 2
INDIVIDUAL_BENEFICIARY = 1

df["risk_score"] = (
     UNKNOWN_BENEFICIARY     * df["is_beneficiary_unknown"]
  + DUPLICATE_PAYMENT   * df["is_duplicate_payment"]
  + UNREGISTERED_CONTRACTOR * df["contractor_not_registered"]
  + NO_DESCRIPTION     * df["has_description"]
  + INDIVIDUAL_BENEFICIARY  * df["is_beneficiary_individual"]
).astype(int)

In [67]:
df.head()

,Payment No,Payer Code,Organization Name,Beneficiary Name,Amount,Description,Date,Month,Type,Year,...,Location,Region,Organization,RC,is_beneficiary_individual,is_beneficiary_unknown,is_contractor_registered,has_description,is_duplicate_payment,risk_score
0,1000659426-24,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MUSTAFA LAMI HAUWA,"7,427,547.84",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,0.00,0,0,1
1,1000659418-17,232002001,DEPARTMENT OF PETROLEUM RESOURCES,AJIMI ALI USMAN,"11,132,598.31",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,0.00,0,0,1
2,1000659418-14,232002001,DEPARTMENT OF PETROLEUM RESOURCES,EKPE ELIJAH AKPAN,"7,246,577.97",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,0.00,0,0,1
3,1000659430-5,232002001,DEPARTMENT OF PETROLEUM RESOURCES,MAGAJI GARBA,"5,796,429.59",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,0.00,0,0,1
4,1000659418-8,232002001,DEPARTMENT OF PETROLEUM RESOURCES,ADENIJI TITILAYO OPEYEMI,"7,116,798.49",2020 DPR STAFF UPFRONT PAYMENT,2020-01-29,1,Individual,2020,...,FCT,North Central,DEPARTMENT OF PETROLEUM RESOURCES,NaN,1,0,0.00,0,0,1

In [79]:
df["risk_band"] = pd.cut(
    df["risk_score"],
    bins=[-1, 0, 1, 4, 999],
    labels=["LOW", "MILD", "CONCERNING", "HIGH"]
)

In [81]:
df.to_csv("payments_enriched.csv", index=False)

In [87]:
org.id

id                    int64
Organization Name    object
COFOG Code            int64
MDA                  object
Location             object
Region               object
Organization         object
Acronym              object
Website              object
dtype: object

In [88]:
df = pd.read_csv('payments_enriched.csv')
org = pd.read_excel('Organizations.xlsx')
contr = pd.read_excel("Final.xlsx")

In [95]:
# df["MDA ID"] = 
df = df.merge(org[["Organization Name", "id"]], how="left", on="Organization Name")

In [96]:
df.to_csv("Cleaned.csv", index=False)